- manila/db/sqlalchemy/models.py
lazy='immediate' leads to each relationship being collected when
it is accessed. This results in at least three extra queries when
we query for all share details. lazy='subquery' collects all data
when the query is exected. In this commit we only changed code for
improving the share list with details ("manila list") speed.
This is joint work together with Johannes Kulik.
> Improve share list speed using lazy='subquery'

- .zuul.yaml
- manila/tests/api/v1/test_share_snapshots.py
- manila/tests/api/v1/test_shares.py
- manila/tests/api/v2/test_share_group_snapshots.py
- manila/tests/api/v2/test_share_groups.py
- manila/tests/api/v2/test_share_snapshots.py
- manila/tests/api/v2/test_shares.py
rpc_backend was an old oslo_messaging option
that was deprecated in stable/newton and removed
in master/stein [2], so stop using it in our
unit tests.
The coverage job in manila was always non-voting,
however, a773e31420bfd141682c43d0823d2009078c2fec
added a common coverage job-template from the
openstack-zuul-jobs repository. This change
inadvertently made the non-voting cover job a
voting job.
Our coverage script isn't perfect, it is known
to fail erroneously on non-code changes, and
some genuine failures are just an indication
to developers and reviewers to make the best
effort to adhere to the script's strict
checks [3].
These changes are unrelated, but must be fixed
together to pass the gate, since we have a
chicken-and-egg problem with both failures
preventing separate fixes from …
> [stein] Make coverage non-voting and fix use of rpc_backend

- manila/db/sqlalchemy/models.py
Modeify relationship of ShareSnapshotInstance. Use 'subquery' instead of 'immediate' for lazy options.
> Imporve share snapshot list performance

- manila/db/sqlalchemy/api.py
- manila/db/sqlalchemy/models.py
Improve performance of function `manila.db.sqlalchemy.api.share_instances_get_all_by_host` with argument `with_share_data=True`.
Old implementation loops over the instance list and fetch share for each. It leads to bad performance when instance list is long (>100). Instead, query `share_instances` table with join to `share` table is much more performant.
> Fix get instance parent

- manila/share/manager.py
- manila/tests/share/test_manager.py
Netapp driver does not resize share when reverting to snapshot.
> Skip updating share size when revert-to-snapshot

- manila/db/sqlalchemy/api.py
- manila/tests/db/sqlalchemy/test_api.py
listed by 'created_at' timestamp by default. On the edge-case when
shares are listed with --limit (and --offset) two shares with the
exactly same creation timestamp might switch their postition in the list
and with small limit this means lists can be inconsitent between the
same API calls. This fix is an attempt to use two sort keys be default,
the 'created_at' and 'id' to have consistent results.
> If no sort keys were specified when shares are listed, the shares are

- manila/db/sqlalchemy/api.py
In purge_deleted_records() from db.sqlalchemy.api, the DB transaction
wraps around the processing all tables. It potentially blocks the tables
for long time. The change is that, opening a new transaction for
processing each table. The transactions block the table being processed
for a brief time.
> Improve api performance when purging deleted records.

- manila/api/v1/shares.py
- manila/api/v2/shares.py
- manila/db/api.py
- manila/db/sqlalchemy/api.py
- manila/exception.py
- manila/message/api.py
- manila/message/message_field.py
- manila/scheduler/drivers/filter.py
- manila/scheduler/filters/affinity.py
- manila/scheduler/host_manager.py
- manila/share/api.py
- manila/tests/scheduler/drivers/test_filter.py
- manila/tests/scheduler/filters/test_affinity.py
Based on https://review.opendev.org/c/openstack/manila/+/775201/
with the following changes:
- '__affinity_*' metadata can only be updated or deleted by admin.
- Affinity/Anti-Affinity filters work on actual hosts, not
aggregates level.
- Allow to query metadata by key with any value (by giving * wildcard).
- Extend error messages to point to Affinity/AntiAffinity when respective
filter returns no host and share cannot be scheduled.
> Share Affinity and Anti-Affinity Scheduler filters.

- manila/db/sqlalchemy/models.py
Non-captured exceptions are logged in Sentries while constructing the `migrating_snapshots` list during the API call to list the snapshots. The `share_instance` is `None`, and therefore is not subscriptable. This is a similar fix to 5cf087e1856e9225f204d09b40caeeda1340b785
> Fix non-captured exception from listing snapshots

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
- manila/share/drivers/netapp/options.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_multi_svm.py
The backend config option "netapp_enable_logical_space_reporting=True"
allows to create share server with logical space reporting. This only
works in combination with thin_provisioned volumes.
> Enable logical space reporting

- manila/share/drivers/netapp/dataontap/cluster_mode/drv_multi_svm.py
fail early if ad and ldap security services are missing
to create a multi protocol share
> ccloud: add security service association for multi

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
- manila/share/drivers/netapp/utils.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_base.py
- manila/tests/share/drivers/netapp/dataontap/fakes.py
NetApp Driver: Specify how much inodes (files) should be possible at
maximum depending on volume (share) size.
Possible multipliers are between (0,8].
The default is somewhere around 1 -  meaning, you get 1 inode for each
32 KiB inside a volume - e.g. a 32 GiB share would be allowed to hold
1024*1024 files.
The maximum multiplier 8 is derived from the example table in TR-4617.
Increasing this value, means increasing the max inode count.
E.g. setting max_files_multiplier to 4 would mean you get 1 inode
already for each 8 KiB inside a volume - a 32 GiB share would then
hold 4*1024*1024 files.
Extending volume size will directly proportional increase the inode
count up to the NetApp absolute maximum of around 2 billion files
in a volumes. TR-4617:
"An inode in ONTAP is a pointer to any file …
> ccloud: add extra spec 'netapp:max_files_multiplier'

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
keeps existing setting on update, uses default on new vservers
Change-Id: I43cbe288fd72af40d630abba0c351c7317667065
> ccloud: do not touch nfs v4.0 if it has not been enabled

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
only shrink share is expected to decrease max_files.
This is flawed in a way: setting max_files_multiplier to < 1
may not work as intended in this case.
Change-Id: I94215b212ceccdba151e64cb38db9f26f7fbc1d2
> ccloud: ensure max_files but allow backend overwrite

- manila/db/api.py
- manila/db/sqlalchemy/api.py
- manila/share/access.py
- manila/share/manager.py
applies to access rules which are older than 7 days.
I.e. in the first week it will be re-tried on every ensure run.
Log known errors with lower level.
> ccloud: every 7 days re-try to apply access rules in error state

- manila/share/manager.py
- manila/tests/share/test_manager.py
is required to get it into volume comment
Change-Id: I657c19a74eb561f441dc6749210bfa906687a002
> ccloud: fix missing share type name in share_instance dict

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
If the customer is configuring "Servers" as AD Server in the Security
Service then the domain controller discovery mode should be changed
to "none" and only these servers should be used.
> Set DC discovery-mode to 'none' in case server specified

- doc/source/admin/capabilities_and_extra_specs.rst
- manila/api/openstack/api_version_request.py
- manila/common/constants.py
- manila/share/api.py
- manila/share/share_types.py
- manila/tests/share/test_api.py
- manila/tests/share/test_share_types.py
Allows set max share extend size that can be created in
extra_specs for each share_type.the share size will
be checked at API level as part of share extend. New
extra_specs keys are supported for set max extend size
of share. 'provisioning:max_share_extend_size'
> Adds support max share extend size limited by share_type

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_base.py
This pr patches NetApp driver to set the Volume's space attributes `is_space_reporting_logical` and `is_space_enforcement_logical`. When a new Share is created, the attributes are set to True values. When a Volume is created based on an existing Volume, for example when creating a Share from Snapshot, or when creating a Share replica, the attributes are set to the same values as the source Volume.
> ccloud: Enable logical space reporting for new shares

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
The 'snapmirrored' mirror-state indicates source and target volumes are in snapmirror relation, but this does not mean that they are in sync, as it is ASYNC mirror, there is always delta present which we have to take care by doing updates/resyncs. So allow resync when replica is out_of_sync take care of delta.
> Allow resync if replica is out_of_sync

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
fixes 'invalid start byte' error on loading DER cert which is in bytes format
amends to b54a2f0386cac708252b22584c04cbd80457b188
> cifs der certs

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
SAPCC: re-introduce 77b4e2d47b892e6b369790161257d3bd3c4027f4
not sending the optional 'is-nfsv40-enabled' parameter to 'nfs-service-modify' means it will not be changed, which is relevant for update_vserver in the ensure loop.
I.e. we don't want to disable nfs v4.0 for existing vservers.
Change-Id: I1e2aa559cceede6505578bef38c1a5b2edf2d991
> keep nfs v4.0 setting on existing vservers

- manila/api/v2/share_replicas.py
- manila/db/api.py
- manila/db/sqlalchemy/api.py
- manila/share/api.py
- manila/tests/share/test_api.py
If soft-deleted share instance with that uuid is still existing,
purge it.
Allows to re-create replicas, that were in unrecoverable error state.
Only for context.is_admin.
> create replica: allow to specify uuid

- manila/share/drivers/netapp/dataontap/cluster_mode/data_motion.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
During replica promotion, Manila tries to first update and then break snapmirror before promoting. Data will be synced from old source to target to prevent data lost. However both update and break steps can fail and therefore it can indeed happen. Update snapmirror can fail because of the client is inaccessible for some reason. Break snapmirror can fail because snapmirror quiesce timeout is reached.
We have tried to update snapmirror volumes more frequently by lowering replica update period from 1h to 10mins, which should allevate the data lost issue. But it's not guaranteed. Adding the warning messages in logs will enable us to monitor and debug the such issues.
> sapcc: Add warning on failures during replica promotion

- manila/share/drivers/netapp/dataontap/cluster_mode/data_motion.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_data_motion.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_base.py
We want to have conformity. not only new snapmirrors, but also old ones should have a schedule according to the current 'netapp_snapmirror_schedule' config.
Follows ee5d9917c786a8f2011e5a24ae1e56343e02349a and c53cd6105d55c7401b7cbc035791c680768347a2
Change-Id: I1f8f0d1f58d7f4dc540bf7949c32114b4599912c
> sapcc: update schedule of existing snapmirrors

- manila/db/sqlalchemy/api.py
- manila/network/neutron/api.py
- manila/network/neutron/neutron_network_plugin.py
- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/manager.py
A few notes on the implementations:
* network.neutron.api and network.neutron.neutron_network_plugin is extended to leverage the Neutron API, creating/activating new port bindings.
* Port bindings are tracked in DB table 'network_allocations', to distinguish from the active bindings, the physical network name is used as label of the inactive bindings.
* I try to make the implementation generic. Logic changes only in manila.share.manager. Objects are refreshed when needed, so no logic needs to be changed in driver.
> WIP svm migration

- manila/share/manager.py
- manila/tests/share/test_manager.py
Otherwise the rules that are copied from source share would hang in 'queued_to_apply' forever.
Eventually this calls the driver with update_access(), where it can decide what to do.
Change-Id: Ie7ddd9f631510ba97e92a1eb0eb9a5d944ec1b3b
Closes-Bug: #2000253
> Apply access rules on new share replicas

- manila/api/v1/security_service.py
Both are not needed, in our case netapp is doing discovery then for both: site and dc.
Brings us closer to what is proposed upstream
https://review.opendev.org/c/openstack/manila/+/855220
Change-Id: Iee203f2b313aac51959184fda08c8720c06a706f
> It is okay to not have server and default_ad_site either

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
Don't bail out on an error at a single share server, log the error and continue processing the others.
If vserver is offline, it may be caused by ongoing SVM DR or similar move.
Change-Id: I021bc6cdf2585c8b880fdf6a6e75946e988029e9
> ensure_share_server: catch NetApp errors

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
it will be re-tried by share ensure later.
Fixes issues we have seen on create_share_from_snapshot.
Change-Id: Iac232844d5ef4c7853629109300604df283d7126
> sapcc: don't fail on setting snapdir access on busy volumes

- manila/db/sqlalchemy/models.py
- requirements.txt
Instead of
`<manila.db.sqlalchemy.models.ShareServer object at 0x7f603645bf40>` we now get
```
ShareServer(created_at=datetime.datetime(2023, 4, 18, 15, 44, 43, 741302),
updated_at=datetime.datetime(2023, 4, 19, 10, 18, 59, 614018),
deleted_at=datetime.datetime(2023, 4, 19, 10, 18, 59, 613577),
id='3363dcd4-fcdd-4cfa-b02d-5899fba3d413',
deleted='3363dcd4-fcdd-4cfa-b02d-5899fba3d413',
share_network_subnet_id='8d4365dc-0869-4896-8049-6455f84ad08f', ...)
```
e.g. in error messages of failed purges or in interactive shell sessions.
Change-Id: I5e6513e7ca7b4a9d4d7261f873cbf3f5bf3c83ab
> sqlalchemy: add generic repr to base model

- manila/db/api.py
- manila/db/sqlalchemy/api.py
- manila/scheduler/host_manager.py
- manila/scheduler/manager.py
- manila/share/api.py
- manila/tests/scheduler/test_host_manager.py
The scheduler need to estimate the allocated capacity for thin
provisioning hosts. To do this more efficiently, use a sum fucntion in
query, instead of loading all share instances for a specific host.
> Improve scheduler performance for thin provisioning

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
- manila/share/drivers/netapp/options.py
- manila/tests/share/drivers/netapp/dataontap/client/fakes.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_multi_svm.py
- manila/tests/share/drivers/netapp/dataontap/fakes.py
The certificate is automatically created on NetApp with 1 year i.e. 365 days of expiration time, and admin needs to manually extend it. It would be nice Manila can take care to create certs with admin configuable expiration time. Manila can first delete the cert, and then create a new cert with given expiration time while creating share server.
> Recreate security cert during vserver create.

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
We have been accumulating thousands of those rules. Apparently ontap does not check if such rule is already existing.
Change-Id: I73b02b05c8a3ba6f0eeda0f87f444cb12c550445
> ensure share server: skip default policy rules

- manila/message/message_field.py
- manila/share/manager.py
When share creation fails due to missing ports quota (' manila.exception.PortLimitExceeded: Maximum number of ports exceeded.'), error message propogated to user is not useful. Improve user message in this scenario.
> propogate port quota limit exceeded error

- manila/share/manager.py
ensure driver resources ->
get all share instances from db ->
loop over share instances ->
share server has been deleted in the meantime
Ignore deleted share server, log warning and move to next share instance.
> Ignore delete share servers in ensure_driver_resources

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
ensure will apply this to all existing vservers. But not for pfns, this will be left untouched and only new vservers will get the default value. This default value is 'false' beginning with ONTAP 9.8, see https://docs.netapp.com/us-en/ontap/nfs-admin/enable-disable-pnfs-task.html
Background: we had trouble with HANA corruption, most likely related to the delegation settings.
Change-Id: Iaad11a79cdbd6955a229eaa20c3320492b87a940
> sapcc: go back to default settings for nfsv41

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
Modify_volume() makes NetApp API call 'volume-modify-iter', but response of API call is not validated against possible errors difficult to debug failure. For example, observed that volume comment not being set on volume created from snapshot (likely due to busy doing clone split)
> Add error handling in modify_volume()

- manila/share/manager.py
if share server details key 'skip_ensure' is set to 'yes' skip the share server ensure run and log a message with the reason given at key 'skip_ensure_comment'
e.g.
```
2023-06-02 09:25:17,935 9 INFO manila.share.manager [req-XXX gNone - - - - -] Share server 7fd26b08-3b4e-42b6-bf75-1c312b80c8ab: skipping export, because it has skip_ensure flag set with reason 'special vserver nfs config for valued client Z'.
```
Change-Id: I5632706ef201c48949544057be4db93ff2f8aff3
> sapcc: skip ensure share server on flag

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
most likely the setting will be already set to 'false' anyway and this way extend and shrink can happen
Change-Id: I6703d52e0ee475cf1cf652aff6e95eebd06ec1e1
fixes #105
> NetApp: don't raise filesys-size-fixed on svm migrate

- manila/api/common.py
- manila/api/v1/share_snapshots.py
- manila/api/v1/shares.py
- manila/common/constants.py
- manila/share/api.py
- manila/tests/api/v1/test_share_snapshots.py
- manila/tests/api/v1/test_shares.py
- manila/tests/share/test_api.py
- releasenotes/notes/bug-1475351-handle-successful-deletion-of-snapshot-if-quota-commit-fails-4d150bf0b71a2fd9.yaml
When manila snapshot fails to create either due to DB error or quota error, an exception raised. But this exception fails to delete snapshot in db due to wrong db api call. Fix it by validating presence of snapshot in db and using correct db api calls.
> Delete failed snapshot entry using correct db api

- manila/scheduler/filters/affinity.py
Comparing host name with '==' instead of 'in' operator.
> fix scheduler's anti affinity filter

- custom-requirements.txt
The package `pyreloader` can reload the service on SIGHUP. It makes debugging easier in the k8s container. To use it, just start the service with pyreloader. E.g. `dumb-init pyreloader maila-share ...`.
> Add pyreloader to custom requirements

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_base.py
When creating a share from Snapshot and clone split needed, we want to postpone it to the last step. But it didn't happen as expected. The split controlling variable is overriden by share type specs. This PR fixes the issue by explictly reading the corresponding specs option into the controlling vairable. Fixes issue https://github.com/sapcc/manila/issues/118.
> sapcc: fix postponing "clone split" to last step

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_base.py
We want to delay split clone to avoid "Volume busy" errors.  However, previous fix dd13d5a does not work properly, see the issue #118. This is also a rework of #117, which follows the fix and did not consider that `split` argument should take precedence over the `split` field in `provisioning_options`.
> Fix delay clone split when creating share from snapshot

- manila/share/api.py
- manila/tests/share/test_api.py
error is no popping up, on the other hand not throwing the excpetion causes inconsistencies (shares reporting wrong AZ)
Change-Id: I562a4bfb3339b738c4d67f78166bbc3e1b3b0a11
undo https://github.com/sapcc/manila/commit/ed19c196df72a3bdac833364c8c8868765b7d542
> sapcc: raise again on share from snap az mismatch

- manila/api/v1/share_snapshots.py
- manila/api/views/share_snapshots.py
- manila/db/api.py
- manila/db/sqlalchemy/api.py
- manila/share/api.py
- manila/tests/api/v2/test_share_snapshots.py
- manila/tests/db/sqlalchemy/test_api.py
Added support for display count info in share snapshot list&detail APIs:
1. /v2/snapshots?with_count=True
2. /v2/snapshots/detail?with_count=True
Note - New version added 2.79 in upstream master and not in xena-m3.
Closes-bug: #2024556
> Add count info in 'snapshot list' API

- manila/db/sqlalchemy/api.py
- manila/tests/db/sqlalchemy/test_api.py
Share/Snapshot list API return count of shares/snapshots. But it return the wrong count as it consider ShareInstances/SnapshotInstances. So filter queries by unique share_id/snapshot_id.
> Fix count response of shares/snapshots list API

- manila/api/v2/share_networks.py
- manila/tests/api/v2/test_share_networks.py
Share network subnet is deleted during share network deletion which was missing earlier causing lots of stale db entries.
Change-Id: Idb58b4ca389cfb1aaf8f9f1f8aa2fd15979c4872
> Delete share network subnet during network deletion

- manila/network/neutron/neutron_network_plugin.py
network_type should not be empty when extending networks with new network allocations
e.g. in NetApp driver the network type is important to determine the multi-tenancy, i.e. usage of ipspaces or not
Change-Id: If665346925c1000a47962248fff712069d7cd529
> fix port network type

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
- manila/tests/share/drivers/netapp/dataontap/fakes.py
Instead of using the identifier the migration methods are deriving the vserver name from the share server id. This causes failure for migrate a share server that had been migrated before.
> Use share server name from share server identifier

- manila/cmd/share.py
- manila/service.py
- manila/share/manager.py
This patch allows to start a Share service with argument reexport by passing cli option '--reexport'.
Change-Id: Ic436124f705b029323bb75ccead86516de7ea2c9
> Start reexport service via cli option

- manila/api/v1/shares.py
- manila/share/manager.py
- manila/tests/share/test_manager.py
This PR includes two patches to improve debugging experiences.
- Add details after share is created by share manager. We can find the created share with request id in logs.
- Log error message with warning level on creating share instance failures.
Change-Id: I5cee640274a43c180b01704104cdf825139fac79
> Improve logging when creating shares

- manila/network/neutron/neutron_network_plugin.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
- manila/share/manager.py
- manila/tests/network/neutron/test_neutron_plugin.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_multi_svm.py
This patch fixes the issue, where sometimes the destination share server is created in Default ipspace on NetApp filer. We make sure that the ipspace name is determined from configuration. The vlan is also ensured to move into the right broadcast domain if it already exists.
> Fix svm mig ipspace

- manila/share/manager.py
- manila/tests/share/test_manager.py
Allow to delay the cleanup of unused share servers to 1 day.
Old setting was capped at 1 hour.
Change-Id: If8f170ffef63532915c34d378529e70bfe72977f
> increase max val for unused_share_server_cleanup_interval

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_base.py
Without this commit, RPO for replica is hardcoded to be 20min.
Asynchronous SnapMirror schedules are set using netapp config option 'netapp_snapmirror_schedule'. The delta for determining replica is in-sync or out-of-sync updated to twice the schedule time seconds. Also, not only new snapmirrors, but also old ones should have a schedule according to the current
'netapp_snapmirror_schedule' config.
Closes-bug: #1996859
Depends-On: I0390f82dfdc130d49e3af6928996dd730e3cf69f
Change-Id: Ifbe0575f6c359929344763666e4d93d8c6084e83
> cherry-pick "Update timedelta and old schedules as per netapp_snapmiror_schedule"

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
- manila/share/manager.py
The list that is checked has only share instances that already
got a host field set, i.e. the creation stuck at a late stage
(after scheduling). Those should be recoverable here.
In the NetApp driver: always set the status to 'available'.
In case something goes wrong, the share instance is not returned
at all (and therefore not updated) in favor of setting status to
'error', which would be too invasive in certain situation.
Change-Id: I8e25e2bc8880e587457fd4e8cb3fa62868f29f9c
> sapcc: allow to ensure share instances in 'creating'

- manila/api/v2/share_servers.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
- manila/share/manager.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_multi_svm.py
This patch allows specifying a single pool as destination of server migration using SVM migrate with NetApp Driver.
Change-Id: I659b14f204aabf4515ac97e928bc14a58ef662f0
> allow specify pool as server migration destination

- manila/share/manager.py
- manila/tests/share/test_manager.py
especially shares that ended up in extending_error due to not
having a pool should be fixed here
Change-Id: Ie924e6fbe402a2ca1fb534bde178cd78a3eb5341
> ensure: non busy shares should have pools

- manila/db/sqlalchemy/api.py
The delete operation may have been interrupted by service stop.
Should be picked up and retried.
Change-Id: I432991f86f12ef09e2b1691a7b895742f9220dc6
> share servers in state 'deleting' are deletable

- manila/share/manager.py
- manila/tests/share/test_manager.py
Skip share servers linked to incomplete migrations in periodic cleanup job. Deleting them risks removing associated objects, such as network ports, unexpectedly. Admins should inspect the affected share servers and cleanup manually.
Change-Id: Ie0e5fa9cd6d527d382f275ba8b3710ee18ef1c0a
> skip auto deleting servers from broken migration

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
During prune deleted volumes option, if volume is offline, manila calls for ONTAP volume-destroy API. However if volume has one or more clones, the destroy operation fails. So upon receving clone related error, check clone spilt status and if not started, start it.
> Fix prune deleted volumes for clones

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
NetApp driver tries to update  export locations for all share instances on the server after server migration is completed on the back end. We could safely continue to next instances if creating export location for one had failed. In most cases, the export locations are not changed during server migration; and Manila ensure will update the share info including the export locations periodically.
Change-Id: I9c2174c55eb1101d085d83e621e224c5add7551f
> [netapp] continue server migration complete on create export errors

- manila/share/manager.py
- manila/tests/share/test_manager.py
Since share instance get call runs in periodic task which run in each manila-share service instance, we better optimize query to consider only current host. This will improve performance.
> Fix deferred deletion get query

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
in case of svm migration from backend we clean the aggregate part of
the host field to let manila ensure rediscover the actual aggregate.
This is currently only done (and supported) for
non flexgroup (i.e. flexvol) shares.
Change-Id: Ib7643d66615ecdb67a80a516f261d8ee670b547d
> ccloud: fallback for flexgroup

- manila/policies/share_snapshot.py
- manila/policies/shares.py
- manila/share/api.py
- manila/tests/api/v2/test_share_accesses.py
- manila/tests/api/v2/test_share_instances.py
- manila/tests/share/test_api.py
Deferred deletion states deferred_deleting, error_deferred_deleting are visible for non-admin user in 'share/snapshot show' command. Fixed this.
Closes-bug: #2067456
Change-Id: I42ddda3144a3f52b4bc0420d5acde1e5e7560264
> Fix share/snapshot show for deferred deletion

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_multi_svm.py
dc config validation may fail, because network connectivity is not
given at that point of setup
run another round with the different discovery modes: to keep current
behaviour in the game
(previously we only set those after cifs-server-create?)
Change-Id: Ia28721444c596878f77a34e204ec9fe9a8a1e714
> sapcc: more attempts at cifs setup

- manila/network/__init__.py
- manila/network/neutron/neutron_network_plugin.py
- manila/network/standalone_network_plugin.py
- manila/share/driver.py
- manila/share/manager.py
Share server deletion if causes any exception, Manila end up having orphaned ports. So first deallocate network and then proceed with share server deletion.
Change-Id: Ibba5326177417bb4e56c19c59040c40b7886d58b
> delete ports before share server deletion

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
- manila/tests/share/drivers/netapp/dataontap/client/fakes.py
- manila/tests/share/drivers/netapp/dataontap/fakes.py
followup to 7f39c185560591df99bbba6b0a05286b925fc17e
We don't need to disable already disabled interfaces, which would
happen on the second and consecutive runs of the cleanup if it failed.
In fact this throws an error
'13005:Unable to find API: net-interface-modify on data vserver'
Change-Id: Ia34809d96097d684113e651e09676b4e8a643054
> improve 'NetApp: start vserver delete by disabling the interfaces'

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
Old share servers may not have the 'ports' in the backend_details.
The old information is not used, it is just to make sure the key is
deleted before overwriting.
Change-Id: I8346a424f9d769eedf4f42e96d6918a5cb92585f
Also see https://docs.python.org/3/library/stdtypes.html#dict.pop
> fix share server migration KeyError

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
If we turn off the vserver interface the vserver api will not work.
Fixes '13005:Unable to find API'
Change-Id: I57612fec5487aa229c4bf933696d00b7906319e6
> use cluster client for interface api

- manila/share/api.py
- manila/share/manager.py
- manila/tests/share/test_manager.py
- Deferred deletion would be regular deletion where quota is freed before resource deletion by driver and deletion states are hidden from end-user. Also, everything will be handled by Manila or admin if any error occurs in deletion.
- Any error during deferred deletion will put share/snapshot in error_deferrer_deleting state and periodic task will handle it.
Change-Id: I7852545b735b3d03096816e65af2a6a9de5c1391
> Update share/snapshot instance deferred deletion

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_multi_svm.py
clean up ipspace/broadcast domain and vlan on source side
Change-Id: I23e8e0e890c146d325232d9e9a2aa8cf13b628e6
> [NetApp] delete source ipspace after server migration completed

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
Orphan vlans are moved to DEFAULT ipspace when their originally associated ipspaces are deleted. As a result, new vserver will be put in the DEFAULT ipspace if it is on an orphan vlan. This PR will ensure a private ipspace is created and used for vserver. The vlans are then moved to the correct ipspace in the following steps.
Change-Id: I285a0e39603b6c144b3b8c8bafe61a48c420899d
> ccloud: prevent new vserver created in cluster ipspaces

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
- releasenotes/notes/bug-2071359-netapp-retry-sis-operatin-if-already-active-4625605175f76d07.yaml
Retry for 5 times, in case dedupe enable/disable failed. E.g. error message contains "Another sis operation is currently active."
Change-Id: Ia6bddbc06830a5cc8fc64154d4efc68f6fc02141
> Retry Dedupe enable/disable if busy

- manila/db/api.py
- manila/db/sqlalchemy/api.py
- manila/network/neutron/neutron_network_plugin.py
- manila/share/manager.py
- manila/tests/network/neutron/test_neutron_plugin.py
This work follows up PR #60, #146 and #152. In previous PR's, we used a trick to save new segment id associated with target host in the network_allocations table.  Since we only extend network allocations during server migration, there is actually no new network allocations created. Therefore it's complicated to implement and difficult to read the code. More importantly, it introduces non-trivial side effect. In cutover stage, the driver tries to delete the ports and create them again. Only part of them are re-created when migrating a 4-lif share server, leading to losts of network interface. In this PR, we save the segment id in the backend details of the destination share server instead. The port-lost problem is avoided without the need of modifying driver.
Change-Id: …
> Improve server migration

- manila/share/manager.py
- manila/tests/share/test_manager.py
in the meantime the share may have been deleted and
we don't want to update the status.
Especially with deferred deletion, shares are longer in that state,
where the backend share is still existing, i.e. the driver ensure
operations are working normally, but still we don't want to reset the
status to available.
followup to 24fb551ee4098fc219bc31b77895b2a8ef463d66
Change-Id: Ie949153e1bc2b854c4263f1899784b9dfe6ec094
> sapcc: double check status in second ensure loop

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
by default it would be disabled.
It can only be enabled after cifs server has been created.
Therefore this can not be coupled with the other cifs security settings
that are handled in configure_cifs_encryption() before cifs server
creation.
equivalent to ontap client
'vserver cifs security modify -is-signing-required true [...]'
Change-Id: I3f1bbf009f47ebcb00c4c19206e08f11a87da9f3
> cifs: enable SMB signing

- manila/share/drivers/netapp/dataontap/client/api.py
The same is already logged in the init of BaseClient, the parent of
ZapiClient, which gets initialized a few lines above.
Change-Id: I6cd6aa261d3fd29a162c1f7d51d7374894b5565f
> NetApp: remove duplicated debug log

- manila/db/sqlalchemy/api.py
If running with invalid db config, we get no tables and
the command silently finished. Change that and raise some
suspicion instead.
Change-Id: I8d45b4da1d586c83ab82b56af7c8770a9c4dcd1e
> db purge: raise on missing tables

- manila/db/sqlalchemy/models.py
The ShareInstance model has relationships with AvailabilityZone and
ShareType models. These relationships are loaded lazily by subquery.
This emits sql queries for availability zone and share type with
subquery for all share instances, which is not efficient as the share
instance table grows. This change modifies the relationships to load the
availability zone and share type with selectin load, which will load all
items from the availability zone and share type tables in a single
query. It's acceptable because they are pretty small tables.
Reference for selectin loading: [link](https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html#selectin-eager-loading)
Change-Id: I0525b8cff6616e4e6f290de50dcdd50e1b7435d8
> modify lazy loading for ShareInstance model

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
When creating a share from snapshot (NetApp volume clone),
the parent snapshot is being copied into the child volume.
This is not expected/not being tracked by manila. So we handle the
soft deletion of that snapshot. It cannot be deleted immediately,
because the clone split needs to finish first.
Change-Id: I2556efe187d259f6624573f6690e89d05d554089
> NetApp: take care to remove parent snapshot in child share

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
follow up to 688d856f31597ff27f678df6452e2c53aa4008eb
Now we have it enabled everywhere, we don't need to ensure this.
On demand we may even disable again(?).
If we want to enable this again, the code should be improved to
first check if it is already enabled, and send the enable call only
if necessary.
Change-Id: I40533ec3f40e53f06098260e2290247dd386878e
> cifs: don't ensure smb signing

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
- manila/share/manager.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_base.py
- manila/tests/share/test_manager.py
- releasenotes/notes/bug-2064502-netapp-fix-revert-to-snapshot-f23ab4dc325b2c42.yaml
For NetApp ONTAP, revert to snapshot consider the largest size between original share size and snapshot size after revert is done. This is different from generic approach where share size is updated to snapshot size blindly. Fixed this.
Change-Id: I7be842df601d9409f4b4040357f7048eca479eac
> Handle revert to snapshot for NetApp

- manila/db/sqlalchemy/api.py
- manila/share/api.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
We are managing a NetApp volume, which was in Manila db, but currently not. We would like to keep the backend configurations unchanged, including volume name, junction-path, export-policy and etc. With this PR, we can achieve this by providing a driver option, i.e. "--driver-options instance_id=[uuid from volume nanme]". 
NOTE: This PR does not guarantee export policy rules are imported into manila DB. Updating share access rule may overwrite policy rules.
Change-Id: I7fa4788e6448e4f3b46258fa0da937cf2968d259
> Keep NetApp volume's name when managing it

- manila/share/api.py
removes the need to do extra API calls to check and reset the status.
Allow to to force extend on extending_error.
Allow to shrink on shrinking_error.
Change-Id: Ic6939e00960e9edae651036848436476b8610b8e
bonus for sapcc: autoscaling is using force and will be able to retry without additional action needed
(I think this is better than always magically resetting the state internally or via nanny)
> allow force extend on shares in extending_error

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_base.py
We need the hostname to match metrics from netapp exporters.
Change-Id: Iec9c9d2a77e0054565697b14779c87c6003377ec
> sapcc: add netapp host in capabilities

- manila/db/sqlalchemy/api.py
- manila/tests/api/v2/test_share_network_subnets.py
- manila/tests/db/sqlalchemy/test_api.py
- manila/tests/db_utils.py
In addition to solely relying on `deleted_at` column set, the purge
method now also checks the `deleted` column to safeguard only purging
records that really have been soft-deleted.
Outcome of an incident, where a soft-deleted record had been
restored/undeleted, but without touching the deleted_at field.
The idea was to not touch deleted_at at that time to have some history
on that previous delete. Now this history is only available for share
instances with the `terminated_at` column.
Change-Id: I23105561a2d7cc65d99da7f4d39d51886ea15a26
> db purge_deleted_records: make sure that entries are soft-deleted

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_single_svm.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_multi_svm.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_single_svm.py
Since ensure_share and housekeeping task both run periodically, it create race condition sometimes. Moving all prune deletion/cleanup tasks to ensure_shares to fix.
Change-Id: I59f15077dd8c5f2977e28d196e0af4cbc1c74c56
> Move prune deletion tasks to ensure_shares.

- manila/api/v1/share_servers.py
- manila/db/sqlalchemy/api.py
- manila/tests/api/v1/test_share_servers.py
Use search options in DB query to filter share servers. This should be
faster than fetching all share server entries then filtering them in
memory.
Change-Id: Ibc043d9975fe611d74d380aa9732020d5cc7759b
> sapcc: improve listing share servers with search option

- manila/share/manager.py
- **sapcc: continue to next share server when error raised**
- **sapcc: continue to ensure next share instance on NotFound error**
> fix ensure

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
Param 'size' of 'volume-create-async' must be an integer,
but it must stay a string at 'volume-create'.
Change-Id: I3332c873a683fa9710f9b117dffe1c0d8ec2b9fb
> provisioning with net capacity: flexgroup size fix

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
don't make the loop stop on error, we want to try pruning again in the
next run.
The prune deleted volumes was operating on deleted volumes (type DEL)
that were already in the recovery queue. Those should not be touched,
they don't need to be brought back online to solve clone split
situations. We are only interested in type RW. So we also don't do
housekeeping on e.g. DP volumes.
Anyway we also catch errors on split start now for a smoother
continuation of the loop.
Change-Id: I7a3c83423d731c4922c8f0f570fa9309fc70db46
> sapcc: improve error handling on prune deleted volumes

- manila/api/openstack/wsgi.py
in addition to x-compute-request-id to be conform with other
services.
This allows for maintaining less special cases e.g. in auditing and
logging.
Change-Id: I59d4bd74db603dd58ba71b7eaeb2f4417895a337
> add x-openstack-request-id header

- manila/api/v1/share_servers.py
It can happen that the field share_network_subnet_id of share server is
None, when e.g. share server is in error state.
Change-Id: I82ea51659d96121cb62bc23efc080ac8cd2ad629
> Fix share server list API

- manila/message/message_field.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
- manila/share/drivers/netapp/options.py
allows to set snapshot policy names that will be kept during ensure
instead of overwriting with the snapshot policy that is set via
share type extra specs.
Moving away from hard coded ec2_backups because new hxm_backups
scenario came up. To ease the setup we default to the known two
options.
Change-Id: I814980966a3ad873ee4e890a5237b336c0040383
> SCI: add config for custom snapmirror policies

- manila/exception.py
- manila/message/message_field.py
- manila/network/neutron/api.py
- manila/share/manager.py
if a neutron subnet is full, no more ports can be created, it raises `IpAddressGenerationFailureClient`
manila catches that exception and raises `PortLimitExceeded`
(Maximum number of ports exceeded.)
This is done in manila/network/neutron/api.py in _create_port() 
```python
except neutron_client_exc.NeutronClientException as e:
LOG.warning('Neutron error creating port on network %s',
network_id)
if e.status_code == 409:
raise exception.PortLimitExceeded()
```
which leads to user message `SHARE_NETWORK_PORT_QUOTA_LIMIT_EXCEEDED`
"Share Driver failed to create share server on share network due to port limit exceeded. You may increase quota of network ports and retry your request [...]"
this is misleading, the problem is not the port quota, but the subnet is out of free IPs
How to …
> [gh-issue#80] Neuton Subnet Full Exception Handling

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
- manila/tests/share/drivers/netapp/dataontap/client/fakes.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_multi_svm.py
We keep deleted volumes (and therefore share servers/vservers) for
a while to be able to restore.
Those entities live in an ipspace that is tied to a neutron subnet
and fixed vlan ID per NetApp storage backend as long as a port is bound
to that backend. Now during delete on manila side the port gets
released which also cleans the vlan ID in neutron if it is the last
one.
If then a new port in the same subnet is bound to that backend it gets
a new vlan ID, but ends up in the same ipspace.
This leads to two vlans in the same ipspace.
When the old volume is ready to be really deleted, vserver cleanup
on manila side tries to delete the ipspace, but won't because it is
still in use and wrongly also did not clean up the vlan.
It assumed wrongly, the vlan would be in use, too. This has been …
> NetApp: delete vlan even if ipspace is reused

- manila/network/neutron/api.py
The goal is to get rid of the port, if it is not found, we reached the
goal. But since it is odd, we log a debug message.
Change-Id: I51e7f3b12643b33e0a44464569b820a37ad75508
> neutron delete port: pass if not found

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_multi_svm.py
It works currently, if the existing ipspace name has the same name
that we would try to create, because create_ipspace in the client
accepts that.
But if the existing ipspace name is different, because we have
multiple neutron subnets, server migration fails.
In the future, once all ipspaces are based on neutron network name
instead of subnet name, this will be needed only on edge cases.
Change-Id: If220727ded0bc796645eb29852d18c23e0a9e8b2
> NetApp share server migration: re use existing ipspace

- manila/api/v1/share_servers.py
follows 081bf70e58e1011f44b35c2e686e01ed62b93fc5
fixes error when writing debug log
```
AttributeError
'ShareServer' object has no attribute 'share_network_id'
```
Change-Id: Ief2bc64c5365676e1e31a4e50582bb556de6b8c6
> followup to share server list fix

- manila/share/manager.py
We iterate over the share network subnets, send rpc calls to delete
their share servers and then remove the share network subnet and the
share network from the db by using soft delete.
The info from those models is still required to deallocate the
network in the driver, e.g. the neutron plugin needs the neutron
net info.
We don't want the API layer of share network delete to be blocked
waiting for share server deletion, instead we look at the soft deleted
data in the manager handling the share server deletion.
This usually happens shortly after the soft deletion was done, so we
should still be able to find the entries.
Change-Id: I1f23b9e93316cabb7bd32be7bb9b63dbd4eb889f
> fix race in share network delete

- manila/share/manager.py
followup to 9189ac305057fa2b9e6f28615ba67a695cff1d00
fixes TypeError
'delete_extended_allocations() takes 3 positional arguments but 4 were given'
Change-Id: I2c659d118d7b156259943e23e61913886768e481
> svm migrate: fix allocation cleanup

- manila/share/api.py
- manila/tests/share/test_api.py
Since we allow share server migration with share replica, we need to make sure correct share and snapshot instances updated to 'server_migrating' status i.e. instances belonging to share server under migration. Fixed this.
Change-Id: I498700367752f2effc8c7a1e50a233579607a9fc
> Fix 'server_migrating' status of non-active replica
