- manila/scheduler/filters/affinity.py
- manila/scheduler/filters/share_replication.py
- manila/share/api.py
> replicate different backend

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
configure certs, use ldaps and signed sessions for active directory
Change-Id: Id50894f9dda06741d05949e41817ba340f17dd2c
> ccloud: report CIFS only when channel binding is available

- manila/scheduler/evaluator/evaluator.py
- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
- manila/tests/scheduler/evaluator/test_evaluator.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
configure certs, use ldaps and signed sessions for active directory
fail unit test if certs would expire in less than 60 days
Change-Id: Id50894f9dda06741d05949e41817ba340f17dd2c
> ccloud: test server certificates validity

- manila/api/v1/security_service.py
Allow update of password in security service for manila
> Allow update of password in security service

- manila/share/drivers/netapp/dataontap/cluster_mode/data_motion.py
- manila/share/drivers/netapp/options.py
Change asynchronous SnapMirror schedules from 1 hour to 10 mins. Also made this configurable via option 'netapp_snapmirror_schedule'.
> [Netapp] Change asynchronous SnapMirror schedules

- manila/share/api.py
- manila/share/share_types.py
- manila/tests/share/test_share_types.py
For create - min and max limit
For shrink - min limit
For extend - max_extend limit (only non-admin)
> Filter on size based on operation.

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
solves error 'Modification of the following fields: files not allowed for volumes of the type "Flexible volume - DP read-only volume"'
Change-Id: Ia61350837ccf8bd692c117fb85e239dbaa7bcb47
> sapcc: fix ensure for replicas

- tools/check_exec.py
use /usr/bin/env python3
Change-Id: I517e7245492ee68b25675628366998456173959a
> check_exec: /usr/bin/python3 bad interpreter

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
There is no rollback. We don't want to come to the situation again, that we have an unfinished promote. It later got completely damaged by an attempted repair in the periodic `update_replica_state`.
Also we had a case, where we don't know why the
`if effi_opts['cross_dedup_disabled']` codepath was taken with an efficiency policy seemingly set to 'auto' (not 'inline-only') all the time. Add logging for more insights the next time.
Change-Id: Iaa02525f70e557d98b33dc9fb5ce8c6afa440118
> sapcc: try blocks for all promote additions

- manila/share/manager.py
Change-Id: I737dbc5138c81e6708b9ebae7e7c11622e124a3d
Closes-Bug: #2024578
fixes #101
> skip periodic update on replicas in 'error_deleting'

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/client/rest_endpoints.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
Change-Id: I0aeed5fc15d30335b275f2d237a7e17fc2e176d5
> sapcc: use 9.12 rest api for volume force delete

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
Change-Id: I9b36027afb5229116695cdd6d4a6de8cc5328c08
> sapcc: lower log to debug on ensure errors during svm migrate

- manila/share/api.py
https://bugs.launchpad.net/manila/+bug/2034925
https://github.com/sapcc/manila/issues/123
> fix: delete share should not fail on removing affinity hints [Issue #123]

- manila/network/neutron/neutron_network_plugin.py
When network segment does not exist before extending the share server ports to target host, the segment is expected to be created by port binding. Wait till the segment becomes available and continue.
Change-Id: I49a125df120aebd269018842944e61a988715a43
> server migration: wait for segment created on target host

- manila/network/neutron/api.py
- manila/network/neutron/neutron_network_plugin.py
- manila/tests/network/neutron/test_neutron_plugin.py
- create port
- get network
- show port
> retry on connection error to neutron

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
Currently snapmirror schedule is applied after checking the last transfer timestamp. But we want to always apply  as long as it does not match the Manila configuration.
Change-Id: I207b8a7cb32974acbfff1af08318e8aaa7a5f1e7
> enforce snapmirror schedule to match the configuration

- manila/share/drivers/netapp/dataontap/protocols/nfs_cmode.py
NetApp driver retrieves the junction path in the last step of creating/updating volumes. We observer that the operation has failed sometimes, because the backend volume is busy presumably. Since the volume has created successfully at this step, it makes sense to retry a few times instead of raise the failure immediately.
Change-Id: I12fd58d433111a900534b797a621bf78d1fdf8dd
> [netapp] retry get volume junction path

- manila/db/sqlalchemy/api.py
- manila/share/manager.py
- manila/tests/share/test_manager.py
Make sure snapshot instance of share instance should be deleted before share instance deletion.
Change-Id: I17a4e6bd810aaa6a6da9bc672ce1e1161fc3b6ce
> Fix share instance deferred deletion race

- manila/network/neutron/api.py
- manila/network/neutron/neutron_network_plugin.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
- manila/tests/share/drivers/netapp/dataontap/client/fakes.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
- **debug log for orphan port deletion**
- **followup for orphan port deletion**
- **NetApp: start vserver delete by disabling the interfaces**
have a look at the individual commit messages
> handle vserver port delete

- manila/share/manager.py
followup to 72f01f143f7f532ab51ca7c3ec6fb0f4368746e6
share network is not used, it may even be already deleted
Change-Id: I84cc70064a33d790db519acdabcff29e74770f98
> simplify 'Delete queried ports from neutron during share server delete'

- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
Only CIFS export locations are generated. This fix adds NFS exports in
addition.
Change-Id: Iea1b5d760702a691436a5e56faaea87a91c9294f
> (ccloud) fix exports for share with MULTI protocol

- manila/db/sqlalchemy/api.py
- manila/message/message_field.py
- manila/scheduler/filters/affinity.py
Split out from https://github.com/sapcc/manila/commit/2f599d4e75636b82ab729a2606d5a88f80dffb6c
see the individual commits
> Anti-/Affinity antelope backport

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
For parent volume to be deleted, Manila fails to check childs. Fixed this by
- Get all clones of given parent volume
- Online the parent volume
- Start clone split for all clones of given parent volume
By next iteration of prune delete volumes, if all clone split jobs are done, then parent will be offline again but without clones. This will successfully finish volume-destroy request.
Change-Id: Icbb1d8399f3fd61d944ee6c073ebfdcdef8f496f
> [WIP] Consider parent volume in prune deleted volumes

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
Change-Id: I253dcea30c52e9515a90129e067de4a08e32064d
> CIFS: configure encryption type advertised to Kerberos

- manila/scheduler/filters/capacity.py
Change-Id: Iaeb70d0dc411dc1d9f8dc13a00d4494971885f38
> capacity filter: debug for adjusted free virtual

- manila/share/drivers/netapp/dataontap/client/client_cmode.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
- manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py
- manila/share/drivers/netapp/options.py
- manila/tests/share/drivers/netapp/dataontap/client/test_client_cmode.py
- manila/tests/share/drivers/netapp/dataontap/cluster_mode/test_lib_base.py
- releasenotes/notes/bug-2036931-fix-flexgroup-dedup-compression-aeb013a6ef24f610.yaml
see the individual commits, one is just a cherry-pick from upstream
> flexgroup config
